---
name: Build and Publish Molecule Base Images

'on':
  push:
    branches: [main]

jobs:
  build-and-push:
    name: Build Molecule Image (${{ matrix.name }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: debian_latest
            base_image: debian:latest
          - name: debian_bookworm
            base_image: debian:bookworm
          - name: debian_bullseye
            base_image: debian:bullseye
          - name: ubuntu_latest
            base_image: ubuntu:latest
          - name: ubuntu_focal
            base_image: ubuntu:focal
          - name: ubuntu_jammy
            base_image: ubuntu:jammy
          - name: ubuntu_noble
            base_image: ubuntu:noble
          - name: kali_rolling
            base_image: kalilinux/kali-rolling
          - name: kali_release
            base_image: kalilinux/kali-last-snapshot

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Multi-Arch Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: >-
            ${{
              'ghcr.io/' + github.repository_owner + '/molecule-'
              + matrix.name + ':latest'
            }}
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}
